defmodule Amplified.OpenAlex.Work do
  @moduledoc """
  Provides struct and type for a Work
  """

  @type t :: %__MODULE__{
          abstract_inverted_index: map | nil,
          authorships: [Amplified.OpenAlex.Authorship.t()] | nil,
          awards: [Amplified.OpenAlex.Award.t()] | nil,
          best_oa_location: Amplified.OpenAlex.Location.t() | nil,
          biblio: Amplified.OpenAlex.WorkBiblio.t() | nil,
          citation_normalized_percentile:
            Amplified.OpenAlex.WorkCitationNormalizedPercentile.t() | nil,
          cited_by_count: integer | nil,
          cited_by_percentile_year: Amplified.OpenAlex.WorkCitedByPercentileYear.t() | nil,
          content_url: String.t() | nil,
          counts_by_year: [Amplified.OpenAlex.WorkCountsByYear.t()] | nil,
          created_date: Date.t() | nil,
          display_name: String.t() | nil,
          doi: String.t() | nil,
          funders: [Amplified.OpenAlex.DehydratedFunder.t()] | nil,
          fwci: number | nil,
          has_content: Amplified.OpenAlex.WorkHasContent.t() | nil,
          id: String.t() | nil,
          ids: Amplified.OpenAlex.WorkIds.t() | nil,
          indexed_in: [String.t()] | nil,
          is_paratext: boolean | nil,
          is_retracted: boolean | nil,
          keywords: [Amplified.OpenAlex.WorkKeyword.t()] | nil,
          language: String.t() | nil,
          locations: [Amplified.OpenAlex.Location.t()] | nil,
          mesh: [Amplified.OpenAlex.WorkMesh.t()] | nil,
          open_access: Amplified.OpenAlex.OpenAccess.t() | nil,
          primary_location: Amplified.OpenAlex.Location.t() | nil,
          primary_topic: Amplified.OpenAlex.WorkTopic.t() | nil,
          publication_date: Date.t() | nil,
          publication_year: integer | nil,
          referenced_works: [String.t()] | nil,
          referenced_works_count: integer | nil,
          related_works: [String.t()] | nil,
          sustainable_development_goals:
            [Amplified.OpenAlex.WorkSustainableDevelopmentGoals.t()] | nil,
          title: String.t() | nil,
          topics: [Amplified.OpenAlex.WorkTopic.t()] | nil,
          type: String.t() | nil,
          updated_date: DateTime.t() | nil
        }

  defstruct [
    :abstract_inverted_index,
    :authorships,
    :awards,
    :best_oa_location,
    :biblio,
    :citation_normalized_percentile,
    :cited_by_count,
    :cited_by_percentile_year,
    :content_url,
    :counts_by_year,
    :created_date,
    :display_name,
    :doi,
    :funders,
    :fwci,
    :has_content,
    :id,
    :ids,
    :indexed_in,
    :is_paratext,
    :is_retracted,
    :keywords,
    :language,
    :locations,
    :mesh,
    :open_access,
    :primary_location,
    :primary_topic,
    :publication_date,
    :publication_year,
    :referenced_works,
    :referenced_works_count,
    :related_works,
    :sustainable_development_goals,
    :title,
    :topics,
    :type,
    :updated_date
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      abstract_inverted_index: :map,
      authorships: [{Amplified.OpenAlex.Authorship, :t}],
      awards: [{Amplified.OpenAlex.Award, :t}],
      best_oa_location: {Amplified.OpenAlex.Location, :t},
      biblio: {Amplified.OpenAlex.WorkBiblio, :t},
      citation_normalized_percentile: {Amplified.OpenAlex.WorkCitationNormalizedPercentile, :t},
      cited_by_count: :integer,
      cited_by_percentile_year: {Amplified.OpenAlex.WorkCitedByPercentileYear, :t},
      content_url: :string,
      counts_by_year: [{Amplified.OpenAlex.WorkCountsByYear, :t}],
      created_date: {:string, "date"},
      display_name: :string,
      doi: :string,
      funders: [{Amplified.OpenAlex.DehydratedFunder, :t}],
      fwci: :number,
      has_content: {Amplified.OpenAlex.WorkHasContent, :t},
      id: :string,
      ids: {Amplified.OpenAlex.WorkIds, :t},
      indexed_in: [:string],
      is_paratext: :boolean,
      is_retracted: :boolean,
      keywords: [{Amplified.OpenAlex.WorkKeyword, :t}],
      language: :string,
      locations: [{Amplified.OpenAlex.Location, :t}],
      mesh: [{Amplified.OpenAlex.WorkMesh, :t}],
      open_access: {Amplified.OpenAlex.OpenAccess, :t},
      primary_location: {Amplified.OpenAlex.Location, :t},
      primary_topic: {Amplified.OpenAlex.WorkTopic, :t},
      publication_date: {:string, "date"},
      publication_year: :integer,
      referenced_works: [:string],
      referenced_works_count: :integer,
      related_works: [:string],
      sustainable_development_goals: [{Amplified.OpenAlex.WorkSustainableDevelopmentGoals, :t}],
      title: :string,
      topics: [{Amplified.OpenAlex.WorkTopic, :t}],
      type: :string,
      updated_date: {:string, "date-time"}
    ]
  end
end
